import { useEffect, useMemo, useRef, useState } from "react";
import { Link } from "react-router-dom";
import { LineChart, Line, XAxis, YAxis, Tooltip, ResponsiveContainer, CartesianGrid } from "recharts";
import { api } from "../services/api";
import DashboardStatCard from "../components/DashboardStatCard";
import RiskDonut from "../components/RiskDonut";
import RiskBadge from "../components/RiskBadge";
import FraudRingHub from "../components/FraudRingHub";
import type {
  AdminDashboardSummary,
  Alert,
  AlertStatus,
  AuditLogEntry,
  FraudNetworkGraphData,
  FraudRing,
  FraudTrendPoint,
  RiskDistributionItem,
  RiskLevel,
  SuspiciousCustomer,
  SuspiciousFingerprint,
} from "../types";

const RISK_LINE_COLORS: Record<string, string> = { low: "#10b981", medium: "#f59e0b", high: "#ef4444", confirmed: "#7c3aed" };

const STATUS_META: Record<AlertStatus, { label: string; pill: string }> = {
  NEW: { label: "New", pill: "bg-blue-50 text-blue-600 dark:bg-blue-500/10 dark:text-blue-400" },
  INVESTIGATING: { label: "Under Review", pill: "bg-amber-50 text-amber-600 dark:bg-amber-500/10 dark:text-amber-400" },
  CONFIRMED_FRAUD: { label: "Confirmed", pill: "bg-red-50 text-red-600 dark:bg-red-500/10 dark:text-red-400" },
  FALSE_POSITIVE: { label: "Clean", pill: "bg-emerald-50 text-emerald-600 dark:bg-emerald-500/10 dark:text-emerald-400" },
  RESOLVED: { label: "Resolved", pill: "bg-slate-100 text-slate-600 dark:bg-white/10 dark:text-slate-300" },
};

const SEVERITY_PILL: Record<string, string> = {
  LOW: "bg-emerald-50 text-emerald-600 dark:bg-emerald-500/10 dark:text-emerald-400",
  MEDIUM: "bg-amber-50 text-amber-600 dark:bg-amber-500/10 dark:text-amber-400",
  HIGH: "bg-red-50 text-red-600 dark:bg-red-500/10 dark:text-red-400",
  CRITICAL: "bg-red-100 text-red-700 dark:bg-red-500/20 dark:text-red-300",
};

const RISK_FACTOR_COLORS = ["bg-red-500", "bg-amber-500", "bg-blue-500", "bg-violet-500", "bg-slate-400"];

const ICONS = {
  transactions: "M3 10h18M7 15h1m4 0h5M5 6h14a2 2 0 012 2v8a2 2 0 01-2 2H5a2 2 0 01-2-2V8a2 2 0 012-2z",
  triangle: "M10.29 3.86l-8.18 14.02A2 2 0 004 21h16a2 2 0 001.89-3.12L13.71 3.86a2 2 0 00-3.42 0zM12 9v4m0 4h.01",
  bell: "M18 8a6 6 0 10-12 0c0 7-3 9-3 9h18s-3-2-3-9M13.73 21a2 2 0 01-3.46 0",
  checkCircle: "M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z",
  xCircle: "M9 9l6 6m0-6l-6 6M21 12a9 9 0 11-18 0 9 9 0 0118 0z",
  gauge: "M12 8v4l3 2M12 21a9 9 0 100-18 9 9 0 000 18z",
  bulb: "M9 18h6M10 21h4M12 3a6 6 0 00-3.5 10.9c.4.3.5.8.5 1.3V16h6v-.8c0-.5.1-1 .5-1.3A6 6 0 0012 3z",
  search: "M11 4a7 7 0 100 14 7 7 0 000-14zM21 21l-4.35-4.35",
  refresh: "M4 4v5h5M20 20v-5h-5M4 9a8 8 0 0114-4.9M20 15a8 8 0 01-14 4.9",
};

type QuickRange = "7d" | "30d" | "90d" | "all";
type TrendZoom = "7D" | "30D" | "90D";
type CustomerRiskFilter = "ALL" | RiskLevel;
type AlertRiskFilter = "ALL" | RiskLevel;
type AlertStatusFilter = "ALL" | AlertStatus;

const PAGE_SIZE = 6;

function isoDate(d: Date): string {
  return d.toISOString().slice(0, 10);
}

// Honest, simple trend read: compares the average of the earlier half of the
// selected range to the later half. Returns undefined when there isn't
// enough data to say anything meaningful, rather than inventing a number.
function halfOverHalfDelta(series: number[]): number | undefined {
  if (series.length < 4) return undefined;
  const mid = Math.floor(series.length / 2);
  const avg = (arr: number[]) => arr.reduce((a, b) => a + b, 0) / (arr.length || 1);
  const before = avg(series.slice(0, mid));
  const after = avg(series.slice(mid));
  if (before === 0) return undefined;
  return ((after - before) / before) * 100;
}

// Alert `reason` text is a free-form sentence generated by the risk engine
// (see backend app/ai/risk_engine.py). This buckets it into the short label
// the table/risk-factor widgets show, based on the language the engine
// actually uses for each signal.
function classifyReason(reason: string | null | undefined): string {
  if (!reason) return "Normal";
  const r = reason.toLowerCase();
  if (r.includes("minutes for this customer") || r.includes("velocity")) return "Velocity";
  if (r.includes("device")) return "Device";
  if (r.includes("location")) return "Location";
  if (r.includes("amount") || r.includes("average") || r.includes("spends")) return "Amount";
  if (r.includes("hour")) return "Unusual Hour";
  if (r.includes("new account")) return "New Account";
  return "Normal";
}

const REASON_LABELS: Record<string, string> = {
  Velocity: "Transaction Velocity",
  Device: "New Device",
  Location: "Location Mismatch",
  Amount: "Unusual Amount",
  "Unusual Hour": "Off-Hours Activity",
  "New Account": "Multiple Accounts",
  Normal: "Normal Activity",
};

function timeAgo(dateStr: string): string {
  const diffMs = Date.now() - new Date(dateStr).getTime();
  const mins = Math.floor(diffMs / 60000);
  if (mins < 1) return "just now";
  if (mins < 60) return `${mins}m ago`;
  const hours = Math.floor(mins / 60);
  if (hours < 24) return `${hours}h ago`;
  const days = Math.floor(hours / 24);
  return `${days}d ago`;
}

function CustomTrendTooltip({ active, payload, label }: any) {
  if (!active || !payload || !payload.length) return null;
  const get = (key: string) => payload.find((p: any) => p.dataKey === key)?.value ?? 0;
  const high = get("high");
  const medium = get("medium");
  const confirmed = get("confirmed");
  const avgTotal = high * 3 + medium * 2 + get("low");
  const denom = high + medium + get("low") || 1;
  const avgScore = ((avgTotal / denom) * 20).toFixed(1);
  return (
    <div className="bg-white dark:bg-[#1a2140] border border-slate-100 dark:border-white/10 rounded-xl shadow-soft px-4 py-3 text-xs min-w-[170px]">
      <div className="font-semibold text-slate-700 dark:text-slate-200 mb-2">{label}</div>
      <div className="space-y-1.5">
        <div className="flex items-center justify-between gap-6">
          <span className="flex items-center gap-1.5 text-slate-500 dark:text-slate-400">
            <span className="w-2 h-2 rounded-full" style={{ background: RISK_LINE_COLORS.high }} /> High Risk
          </span>
          <span className="font-semibold text-slate-700 dark:text-slate-200">{high}</span>
        </div>
        <div className="flex items-center justify-between gap-6">
          <span className="flex items-center gap-1.5 text-slate-500 dark:text-slate-400">
            <span className="w-2 h-2 rounded-full" style={{ background: RISK_LINE_COLORS.medium }} /> Medium Risk
          </span>
          <span className="font-semibold text-slate-700 dark:text-slate-200">{medium}</span>
        </div>
        <div className="flex items-center justify-between gap-6">
          <span className="flex items-center gap-1.5 text-slate-500 dark:text-slate-400">
            <span className="w-2 h-2 rounded-full" style={{ background: RISK_LINE_COLORS.confirmed }} /> Confirmed Fraud
          </span>
          <span className="font-semibold text-slate-700 dark:text-slate-200">{confirmed}</span>
        </div>
      </div>
      <div className="mt-2 pt-2 border-t border-slate-100 dark:border-white/10 flex items-center justify-between">
        <span className="text-slate-400">Avg. Risk Score</span>
        <span className="font-semibold text-slate-700 dark:text-slate-200">{avgScore}</span>
      </div>
    </div>
  );
}

// Custom pill-style dropdown used for the header filters (date range, risk,
// status). Replaces plain <select> elements so the active choice is always
// visible on the button itself, not just on data further down the page.
function HeaderDropdown<T extends string>({
  value,
  options,
  onChange,
  emphasize,
}: {
  value: T;
  options: { value: T; label: string }[];
  onChange: (v: T) => void;
  emphasize?: boolean;
}) {
  const [open, setOpen] = useState(false);
  const ref = useRef<HTMLDivElement>(null);

  useEffect(() => {
    function onDocClick(e: MouseEvent) {
      if (ref.current && !ref.current.contains(e.target as Node)) setOpen(false);
    }
    document.addEventListener("mousedown", onDocClick);
    return () => document.removeEventListener("mousedown", onDocClick);
  }, []);

  const currentLabel = options.find((o) => o.value === value)?.label ?? value;

  return (
    <div className="relative" ref={ref}>
      <button
        type="button"
        onClick={() => setOpen((o) => !o)}
        className={`flex items-center gap-2 text-sm font-semibold px-3 py-2 rounded-xl border shadow-card transition-colors ${
          emphasize
            ? "bg-primary-50 border-primary-200 text-primary-700 dark:bg-primary-500/15 dark:border-primary-500/40 dark:text-primary-300"
            : "bg-white border-primary-100/70 text-slate-600 dark:bg-[#141a2e] dark:border-white/10 dark:text-slate-200"
        }`}
      >
        {currentLabel}
        <svg
          width="12"
          height="12"
          viewBox="0 0 24 24"
          fill="none"
          stroke="currentColor"
          strokeWidth="2.5"
          strokeLinecap="round"
          strokeLinejoin="round"
          className={`transition-transform ${open ? "rotate-180" : ""}`}
        >
          <path d="M6 9l6 6 6-6" />
        </svg>
      </button>
      {open && (
        <div className="absolute right-0 top-[calc(100%+6px)] min-w-[180px] bg-white dark:bg-[#141a2e] border border-primary-100/70 dark:border-white/10 rounded-xl shadow-soft p-1.5 z-30">
          {options.map((opt) => (
            <button
              key={opt.value}
              type="button"
              onClick={() => {
                onChange(opt.value);
                setOpen(false);
              }}
              className={`block w-full text-left text-sm px-3 py-2 rounded-lg transition-colors ${
                opt.value === value
                  ? "bg-primary-50 text-primary-700 font-semibold dark:bg-primary-500/15 dark:text-primary-300"
                  : "text-slate-600 hover:bg-slate-50 dark:text-slate-300 dark:hover:bg-white/5"
              }`}
            >
              {opt.label}
            </button>
          ))}
        </div>
      )}
    </div>
  );
}

export default function AdminDashboardPage() {
  const [range, setRange] = useState<QuickRange>("30d");
  const [dateFrom, setDateFrom] = useState<string>("");
  const [dateTo, setDateTo] = useState<string>("");
  const [refreshTick, setRefreshTick] = useState(0);
  const [trendZoom, setTrendZoom] = useState<TrendZoom>("30D");

  const [summary, setSummary] = useState<AdminDashboardSummary | null>(null);
  const [trend, setTrend] = useState<FraudTrendPoint[]>([]);
  const [chartTrend, setChartTrend] = useState<FraudTrendPoint[]>([]);
  const [riskDist, setRiskDist] = useState<RiskDistributionItem[]>([]);
  const [alerts, setAlerts] = useState<Alert[]>([]);
  const [suspiciousCustomers, setSuspiciousCustomers] = useState<SuspiciousCustomer[]>([]);
  const [suspiciousDevices, setSuspiciousDevices] = useState<SuspiciousFingerprint[]>([]);
  const [suspiciousIps, setSuspiciousIps] = useState<SuspiciousFingerprint[]>([]);
  const [auditLogs, setAuditLogs] = useState<AuditLogEntry[]>([]);
  const [topRing, setTopRing] = useState<FraudRing | null>(null);
  const [ringGraph, setRingGraph] = useState<FraudNetworkGraphData | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [lastRefreshed, setLastRefreshed] = useState<string | null>(null);

  const [customerSearch, setCustomerSearch] = useState("");
  const [customerRiskFilter, setCustomerRiskFilter] = useState<CustomerRiskFilter>("ALL");

  const [alertSearch, setAlertSearch] = useState("");
  const [alertRiskFilter, setAlertRiskFilter] = useState<AlertRiskFilter>("ALL");
  const [alertStatusFilter, setAlertStatusFilter] = useState<AlertStatusFilter>("ALL");
  const [alertPage, setAlertPage] = useState(1);

  // Quick range presets fill in explicit date fields, so the same
  // date_from/date_to params drive every widget below.
  useEffect(() => {
    if (range === "all") {
      setDateFrom("");
      setDateTo("");
      return;
    }
    const days = range === "7d" ? 7 : range === "30d" ? 30 : 90;
    const to = new Date();
    const from = new Date();
    from.setDate(from.getDate() - (days - 1));
    setDateFrom(isoDate(from));
    setDateTo(isoDate(to));
  }, [range]);

  const dateParams = useMemo(
    () => ({
      ...(dateFrom ? { date_from: dateFrom } : {}),
      ...(dateTo ? { date_to: dateTo } : {}),
    }),
    [dateFrom, dateTo]
  );

  // The trend chart has its own 7D/30D/90D zoom control, independent of the
  // "Date Range" header filter above. It always needs the full 90-day window
  // from the backend so every zoom level has real data to slice from — if it
  // instead reused `dateParams`, picking e.g. "Last 7 Days" up top would
  // starve the 90D chart view down to a handful of points, which is what
  // produced the flat-then-spike, broken-looking trend line.
  const trendDateParams = useMemo(() => {
    const to = new Date();
    const from = new Date();
    from.setDate(from.getDate() - 89);
    return { date_from: isoDate(from), date_to: isoDate(to) };
  }, []);

  useEffect(() => {
    let cancelled = false;
    setLoading(true);
    setError(null);

    Promise.all([
      api.get("/dashboard/admin/summary", { params: dateParams }),
      api.get("/dashboard/admin/fraud-trend", { params: dateParams }),
      api.get("/dashboard/admin/fraud-trend", { params: trendDateParams }),
      api.get("/dashboard/admin/risk-distribution", { params: dateParams }),
      api.get("/alerts"),
      api.get("/dashboard/admin/suspicious-customers", { params: { limit: 20 } }),
      api.get("/dashboard/admin/suspicious-devices", { params: { limit: 10, ...dateParams } }),
      api.get("/dashboard/admin/suspicious-ips", { params: { limit: 10, ...dateParams } }),
      api.get("/audit-logs", { params: { limit: 8 } }),
      api.get("/fraud-network/rings", { params: { limit: 1 } }),
    ])
      .then(([s, t, chartT, rd, al, sc, sd, si, logs, rings]) => {
        if (cancelled) return;
        setSummary(s.data);
        setTrend(t.data);
        setChartTrend(chartT.data);
        setRiskDist(rd.data);
        setAlerts(al.data);
        setSuspiciousCustomers(sc.data);
        setSuspiciousDevices(sd.data);
        setSuspiciousIps(si.data);
        setAuditLogs(logs.data);
        const ring: FraudRing | undefined = rings.data?.rings?.[0];
        setTopRing(ring ?? null);
        setLastRefreshed(new Date().toLocaleTimeString());
        if (ring?.customer_ids?.[0]) {
          return api.get(`/fraud-network/graph/${ring.customer_ids[0]}`).then((g) => {
            if (!cancelled) setRingGraph(g.data);
          });
        }
        setRingGraph(null);
      })
      .catch(() => {
        if (!cancelled) setError("Couldn't load dashboard data. Try adjusting the date range or refreshing.");
      })
      .finally(() => {
        if (!cancelled) setLoading(false);
      });

    return () => {
      cancelled = true;
    };
  }, [dateParams, trendDateParams, refreshTick]);

  const totalSeries = useMemo(() => trend.map((t) => t.total), [trend]);
  const highSeries = useMemo(() => trend.map((t) => t.high), [trend]);
  const mediumSeries = useMemo(() => trend.map((t) => t.medium), [trend]);
  const confirmedSeries = useMemo(() => trend.map((t) => t.confirmed), [trend]);

  const zoomedTrend = useMemo(() => {
    const days = trendZoom === "7D" ? 7 : trendZoom === "30D" ? 30 : 90;
    return chartTrend.slice(-days);
  }, [chartTrend, trendZoom]);

  const peakDay = useMemo(
    () => trend.reduce<FraudTrendPoint | null>((max, t) => (t.total > (max?.total ?? -1) ? t : max), null),
    [trend]
  );

  const filteredCustomers = useMemo(() => {
    const q = customerSearch.trim().toLowerCase();
    return suspiciousCustomers.filter((c) => {
      const matchesRisk = customerRiskFilter === "ALL" || c.risk_level === customerRiskFilter;
      const matchesSearch = !q || c.name.toLowerCase().includes(q) || c.customer_id.toLowerCase().includes(q);
      return matchesRisk && matchesSearch;
    });
  }, [suspiciousCustomers, customerSearch, customerRiskFilter]);

  const filteredAlerts = useMemo(() => {
    const q = alertSearch.trim().toLowerCase();
    return alerts.filter((a) => {
      const matchesRisk = alertRiskFilter === "ALL" || a.severity === alertRiskFilter;
      const matchesStatus = alertStatusFilter === "ALL" || a.status === alertStatusFilter;
      const matchesSearch =
        !q || a.transaction_id.toLowerCase().includes(q) || a.customer_id.toLowerCase().includes(q) || a.title.toLowerCase().includes(q);
      return matchesRisk && matchesStatus && matchesSearch;
    });
  }, [alerts, alertSearch, alertRiskFilter, alertStatusFilter]);

  useEffect(() => setAlertPage(1), [alertSearch, alertRiskFilter, alertStatusFilter]);

  const totalAlertPages = Math.max(1, Math.ceil(filteredAlerts.length / PAGE_SIZE));
  const pagedAlerts = filteredAlerts.slice((alertPage - 1) * PAGE_SIZE, alertPage * PAGE_SIZE);

  const topRiskFactors = useMemo(() => {
    if (alerts.length === 0) return [];
    const counts = new Map<string, number>();
    alerts.forEach((a) => {
      const key = classifyReason(a.reason);
      counts.set(key, (counts.get(key) ?? 0) + 1);
    });
    return Array.from(counts.entries())
      .filter(([key]) => key !== "Normal")
      .sort((a, b) => b[1] - a[1])
      .slice(0, 5)
      .map(([key, count], i) => ({
        label: REASON_LABELS[key] ?? key,
        pct: Math.round((count / alerts.length) * 100),
        color: RISK_FACTOR_COLORS[i % RISK_FACTOR_COLORS.length],
      }));
  }, [alerts]);

  const rangeMinutes = useMemo(() => {
    if (!dateFrom || !dateTo) return 30 * 24 * 60;
    const days = Math.max(1, (new Date(dateTo).getTime() - new Date(dateFrom).getTime()) / 86400000 + 1);
    return days * 24 * 60;
  }, [dateFrom, dateTo]);
  const transactionsPerMinute = summary ? Math.max(0.1, summary.total_transactions / rangeMinutes).toFixed(1) : "—";

  const networkRelatedEntities = useMemo(() => {
    const nodes = ringGraph?.nodes ?? [];
    const count = (type: string) => nodes.filter((n) => n.type === type).length;
    return [
      { label: "Users", count: topRing?.customer_ids.length ?? count("customer") },
      { label: "Devices", count: topRing?.shared_device_count ?? count("device") },
      { label: "IP Addresses", count: topRing?.shared_ip_count ?? count("ip") },
      { label: "Locations", count: count("location") },
      { label: "Transactions", count: topRing?.total_suspicious_transactions ?? count("transaction") },
    ];
  }, [ringGraph, topRing]);

  const totalAlertsInRange = summary?.fraud_alerts ?? alerts.length;

  return (
    <div>
      {/* Header */}
      <div className="flex items-start justify-between mb-6 flex-wrap gap-3">
        <div>
          <h1 className="text-2xl font-display font-bold text-slate-900 dark:text-slate-50 mb-1">Dashboard</h1>
          <p className="text-sm text-slate-500 dark:text-slate-400">Monitor transactions, detect fraud and take action in real time.</p>
        </div>

        <div className="flex items-center gap-2 flex-wrap">
          <HeaderDropdown
            value={range}
            onChange={setRange}
            options={[
              { value: "7d", label: "Last 7 Days" },
              { value: "30d", label: "Last 30 Days" },
              { value: "90d", label: "Last 90 Days" },
              { value: "all", label: "All Time" },
            ]}
          />
          <HeaderDropdown
            value={alertRiskFilter}
            onChange={setAlertRiskFilter}
            emphasize={alertRiskFilter !== "ALL"}
            options={[
              { value: "ALL", label: "All Risks" },
              { value: "HIGH", label: "High" },
              { value: "MEDIUM", label: "Medium" },
              { value: "LOW", label: "Low" },
            ]}
          />
          <HeaderDropdown
            value={alertStatusFilter}
            onChange={setAlertStatusFilter}
            emphasize={alertStatusFilter !== "ALL"}
            options={[
              { value: "ALL", label: "All Statuses" },
              { value: "NEW", label: "New" },
              { value: "INVESTIGATING", label: "Under Review" },
              { value: "CONFIRMED_FRAUD", label: "Confirmed" },
              { value: "FALSE_POSITIVE", label: "Clean" },
              { value: "RESOLVED", label: "Resolved" },
            ]}
          />
          <button
            onClick={() => setRefreshTick((n) => n + 1)}
            className="flex items-center gap-1.5 text-sm font-semibold px-3 py-2 rounded-xl bg-white dark:bg-[#141a2e] dark:text-slate-200 border border-primary-100/70 dark:border-white/10 text-slate-600 hover:text-primary-600 hover:border-primary-200 shadow-card transition-colors"
          >
            <svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className={loading ? "animate-spin" : ""}>
              <path d={ICONS.refresh} />
            </svg>
            Refresh
          </button>
        </div>
      </div>

      {error && <div className="bg-red-50 border border-red-200 text-red-700 text-sm rounded-lg px-4 py-2 mb-6">{error}</div>}

      {/* Stat cards */}
      <div className="grid grid-cols-2 sm:grid-cols-3 xl:grid-cols-7 gap-4 mb-6">
        <DashboardStatCard
          label="Total Transactions"
          value={loading ? "—" : summary?.total_transactions ?? 0}
          icon={ICONS.transactions}
          color="blue"
          sparklineData={totalSeries}
          deltaPercent={halfOverHalfDelta(totalSeries)}
        />
        <DashboardStatCard
          label="High Risk"
          value={loading ? "—" : summary?.high_risk_transactions ?? 0}
          icon={ICONS.triangle}
          color="red"
          sparklineData={highSeries}
          deltaPercent={halfOverHalfDelta(highSeries)}
          dim={alertRiskFilter !== "ALL" && alertRiskFilter !== "HIGH"}
        />
        <DashboardStatCard
          label="Medium Risk"
          value={loading ? "—" : summary?.medium_risk_transactions ?? 0}
          icon={ICONS.triangle}
          color="amber"
          sparklineData={mediumSeries}
          deltaPercent={halfOverHalfDelta(mediumSeries)}
          dim={alertRiskFilter !== "ALL" && alertRiskFilter !== "MEDIUM"}
        />
        <DashboardStatCard
          label="Fraud Alerts"
          value={loading ? "—" : summary?.fraud_alerts ?? 0}
          icon={ICONS.bell}
          color="pink"
          barPercent={summary ? Math.min(100, (summary.fraud_alerts / (summary.total_transactions || 1)) * 100 * 6) : 40}
          dim={alertStatusFilter === "RESOLVED"}
        />
        <DashboardStatCard
          label="Confirmed Fraud"
          value={loading ? "—" : summary?.confirmed_fraud ?? 0}
          icon={ICONS.checkCircle}
          color="violet"
          sparklineData={confirmedSeries}
          deltaPercent={halfOverHalfDelta(confirmedSeries)}
          dim={alertStatusFilter !== "ALL" && alertStatusFilter !== "CONFIRMED_FRAUD"}
        />
        <DashboardStatCard
          label="False Positives"
          value={loading ? "—" : summary?.false_positives ?? 0}
          icon={ICONS.xCircle}
          color="teal"
          barPercent={summary ? Math.min(100, summary.false_positive_rate) : 40}
          dim={alertStatusFilter !== "ALL" && alertStatusFilter !== "FALSE_POSITIVE"}
        />
        <DashboardStatCard
          label="Avg. Risk Score"
          value={loading ? "—" : summary?.average_risk_score ?? 0}
          icon={ICONS.gauge}
          color="emerald"
          barPercent={summary ? Math.min(100, summary.average_risk_score) : 40}
        />
      </div>

      {/* Main 2-column layout: content (3/4) + right rail (1/4) */}
      <div className="grid grid-cols-1 lg:grid-cols-4 gap-6">
        <div className="lg:col-span-3 space-y-6">
          {/* Trend + Risk distribution */}
          <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
            <div className="app-card md:col-span-2">
              <div className="flex items-center justify-between mb-4 flex-wrap gap-2">
                <h2 className="font-semibold text-slate-800 dark:text-slate-100 flex items-center gap-1.5">
                  Suspicious Transactions Trend
                  <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" className="text-slate-300 dark:text-slate-600">
                    <circle cx="12" cy="12" r="9" />
                    <path d="M12 16v-4m0-4h.01" />
                  </svg>
                </h2>
                <div className="flex items-center gap-3 text-xs">
                  <span className="flex items-center gap-1.5 text-slate-500 dark:text-slate-400">
                    <span className="w-2 h-2 rounded-full" style={{ background: RISK_LINE_COLORS.high }} /> High Risk
                  </span>
                  <span className="flex items-center gap-1.5 text-slate-500 dark:text-slate-400">
                    <span className="w-2 h-2 rounded-full" style={{ background: RISK_LINE_COLORS.medium }} /> Medium Risk
                  </span>
                  <span className="flex items-center gap-1.5 text-slate-500 dark:text-slate-400">
                    <span className="w-2 h-2 rounded-full" style={{ background: RISK_LINE_COLORS.confirmed }} /> Confirmed Fraud
                  </span>
                  <div className="flex items-center bg-slate-50 dark:bg-white/5 rounded-lg p-0.5 ml-1">
                    {(["7D", "30D", "90D"] as TrendZoom[]).map((z) => (
                      <button
                        key={z}
                        onClick={() => setTrendZoom(z)}
                        className={`px-2 py-1 rounded-md font-semibold transition-colors ${
                          trendZoom === z ? "bg-primary-600 text-white" : "text-slate-500 dark:text-slate-400 hover:bg-white dark:hover:bg-white/10"
                        }`}
                      >
                        {z}
                      </button>
                    ))}
                  </div>
                </div>
              </div>
              <ResponsiveContainer width="100%" height={280}>
                <LineChart data={zoomedTrend} margin={{ left: -12 }}>
                  <CartesianGrid strokeDasharray="3 3" stroke="#eef2f7" />
                  <XAxis dataKey="date" fontSize={11} stroke="#94a3b8" tickLine={false} axisLine={false} />
                  <YAxis fontSize={11} stroke="#94a3b8" tickLine={false} axisLine={false} allowDecimals={false} />
                  <Tooltip content={<CustomTrendTooltip />} />
                  <Line type="monotone" dataKey="high" name="High Risk" stroke={RISK_LINE_COLORS.high} strokeWidth={2.5} dot={false} activeDot={{ r: 5 }} />
                  <Line type="monotone" dataKey="medium" name="Medium Risk" stroke={RISK_LINE_COLORS.medium} strokeWidth={2.5} dot={false} activeDot={{ r: 5 }} />
                  <Line type="monotone" dataKey="confirmed" name="Confirmed Fraud" stroke={RISK_LINE_COLORS.confirmed} strokeWidth={2.5} dot={false} activeDot={{ r: 5 }} />
                </LineChart>
              </ResponsiveContainer>
              {!loading && chartTrend.length === 0 && <p className="text-sm text-slate-400 text-center mt-2">No transactions in this range.</p>}
            </div>

            <div className="app-card">
              <h2 className="font-semibold text-slate-800 dark:text-slate-100 mb-4">Risk Distribution</h2>
              <RiskDonut data={riskDist} />
            </div>
          </div>

          {/* Recent alerts */}
          <div className="app-card">
            <div className="flex items-center justify-between mb-3">
              <h2 className="font-semibold text-slate-800 dark:text-slate-100">Recent Alerts</h2>
            </div>
            <div className="flex items-center gap-2 mb-4 flex-wrap">
              <div className="flex items-center gap-2 bg-slate-50 dark:bg-white/5 border border-slate-100 dark:border-white/10 rounded-lg px-3 py-2 flex-1 min-w-[200px]">
                <svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" className="text-slate-400 shrink-0">
                  <path d={ICONS.search} />
                </svg>
                <input
                  value={alertSearch}
                  onChange={(e) => setAlertSearch(e.target.value)}
                  placeholder="Search by transaction ID, user, merchant..."
                  className="bg-transparent text-sm outline-none w-full text-slate-700 dark:text-slate-200 placeholder:text-slate-400"
                />
              </div>
              <select
                value={alertRiskFilter}
                onChange={(e) => setAlertRiskFilter(e.target.value as AlertRiskFilter)}
                className="text-sm border border-slate-100 dark:border-white/10 bg-slate-50 dark:bg-white/5 dark:text-slate-200 rounded-lg px-2 py-2"
              >
                <option value="ALL">Risk Level</option>
                <option value="HIGH">High</option>
                <option value="MEDIUM">Medium</option>
                <option value="LOW">Low</option>
              </select>
              <select
                value={alertStatusFilter}
                onChange={(e) => setAlertStatusFilter(e.target.value as AlertStatusFilter)}
                className="text-sm border border-slate-100 dark:border-white/10 bg-slate-50 dark:bg-white/5 dark:text-slate-200 rounded-lg px-2 py-2"
              >
                <option value="ALL">Status</option>
                <option value="NEW">New</option>
                <option value="INVESTIGATING">Under Review</option>
                <option value="CONFIRMED_FRAUD">Confirmed</option>
                <option value="FALSE_POSITIVE">Clean</option>
                <option value="RESOLVED">Resolved</option>
              </select>
            </div>
            <div className="overflow-x-auto">
              <table className="w-full text-sm">
                <thead>
                  <tr className="text-left text-xs uppercase tracking-wide text-slate-500 dark:text-slate-400 border-b border-slate-100 dark:border-white/10">
                    <th className="py-2 pr-3">ID</th>
                    <th className="py-2 pr-3">Risk</th>
                    <th className="py-2 pr-3">Score</th>
                    <th className="py-2 pr-3">Reason</th>
                    <th className="py-2 pr-3">Status</th>
                    <th className="py-2 pr-3">Time</th>
                    <th className="py-2 pr-3">Action</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-slate-100 dark:divide-white/5">
                  {pagedAlerts.map((a) => (
                    <tr key={a.id} className="hover:bg-slate-50 dark:hover:bg-white/5">
                      <td className="py-2.5 pr-3 font-mono text-xs text-slate-700 dark:text-slate-300">{a.transaction_id}</td>
                      <td className="py-2.5 pr-3">
                        <span className={`inline-flex px-2.5 py-1 rounded-full text-xs font-semibold ${SEVERITY_PILL[a.severity] ?? SEVERITY_PILL.LOW}`}>
                          {a.severity.charAt(0) + a.severity.slice(1).toLowerCase()}
                        </span>
                      </td>
                      <td className="py-2.5 pr-3 font-semibold text-slate-700 dark:text-slate-200">
                        {a.risk_score != null ? Math.round(a.risk_score) : "—"}
                      </td>
                      <td className="py-2.5 pr-3 text-slate-500 dark:text-slate-400">{classifyReason(a.reason)}</td>
                      <td className="py-2.5 pr-3">
                        <span className={`inline-flex px-2.5 py-1 rounded-full text-xs font-semibold ${STATUS_META[a.status].pill}`}>
                          {STATUS_META[a.status].label}
                        </span>
                      </td>
                      <td className="py-2.5 pr-3 text-slate-400 whitespace-nowrap">{timeAgo(a.created_at)}</td>
                      <td className="py-2.5 pr-3">
                        <Link
                          to={`/alerts/${a.id}`}
                          className="inline-flex items-center px-3 py-1.5 rounded-lg text-xs font-semibold bg-primary-50 text-primary-700 hover:bg-primary-100 dark:bg-primary-500/10 dark:text-primary-300 dark:hover:bg-primary-500/20 transition-colors"
                        >
                          View
                        </Link>
                      </td>
                    </tr>
                  ))}
                  {!loading && pagedAlerts.length === 0 && (
                    <tr>
                      <td colSpan={7} className="py-6 text-center text-slate-400">
                        {alerts.length === 0 ? "No alerts yet." : "No alerts match your filters."}
                      </td>
                    </tr>
                  )}
                </tbody>
              </table>
            </div>
            {filteredAlerts.length > 0 && (
              <div className="flex items-center justify-between mt-4 text-xs text-slate-500 dark:text-slate-400 flex-wrap gap-2">
                <span>
                  Showing {(alertPage - 1) * PAGE_SIZE + 1}–{Math.min(alertPage * PAGE_SIZE, filteredAlerts.length)} of{" "}
                  {alertRiskFilter === "ALL" && alertStatusFilter === "ALL" && !alertSearch ? totalAlertsInRange : filteredAlerts.length}
                </span>
                <div className="flex items-center gap-1">
                  <button
                    onClick={() => setAlertPage((p) => Math.max(1, p - 1))}
                    disabled={alertPage === 1}
                    className="w-7 h-7 flex items-center justify-center rounded-lg border border-slate-100 dark:border-white/10 disabled:opacity-30"
                  >
                    ‹
                  </button>
                  {Array.from({ length: Math.min(5, totalAlertPages) }, (_, i) => i + 1).map((p) => (
                    <button
                      key={p}
                      onClick={() => setAlertPage(p)}
                      className={`w-7 h-7 flex items-center justify-center rounded-lg font-semibold ${
                        alertPage === p ? "bg-primary-600 text-white" : "border border-slate-100 dark:border-white/10 hover:bg-slate-50 dark:hover:bg-white/5"
                      }`}
                    >
                      {p}
                    </button>
                  ))}
                  <button
                    onClick={() => setAlertPage((p) => Math.min(totalAlertPages, p + 1))}
                    disabled={alertPage === totalAlertPages}
                    className="w-7 h-7 flex items-center justify-center rounded-lg border border-slate-100 dark:border-white/10 disabled:opacity-30"
                  >
                    ›
                  </button>
                </div>
              </div>
            )}
          </div>

          {/* Fraud network + Recent activity */}
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            <div className="app-card">
              <div className="flex items-center justify-between mb-3">
                <h2 className="font-semibold text-slate-800 dark:text-slate-100 flex items-center gap-1.5">
                  Fraud Network
                  <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" className="text-slate-300 dark:text-slate-600">
                    <circle cx="12" cy="12" r="9" />
                    <path d="M12 16v-4m0-4h.01" />
                  </svg>
                </h2>
                <Link to="/fraud-network" className="text-sm text-primary-600 hover:underline flex items-center gap-1">
                  View Network →
                </Link>
              </div>
              {ringGraph && ringGraph.nodes.length > 0 ? (
                <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                  <FraudRingHub entities={networkRelatedEntities} height={220} />
                  <div>
                    <div className="text-xs font-semibold text-slate-500 dark:text-slate-400 mb-2">Related Entities</div>
                    <ul className="space-y-2 text-sm">
                      {networkRelatedEntities.map((e) => (
                        <li key={e.label} className="flex items-center justify-between">
                          <span className="text-slate-600 dark:text-slate-300">{e.label}</span>
                          <span className="font-semibold text-slate-800 dark:text-slate-100">{e.count}</span>
                        </li>
                      ))}
                    </ul>
                  </div>
                </div>
              ) : (
                <div className="h-[220px] flex items-center justify-center text-sm text-slate-400 border border-dashed border-slate-200 dark:border-white/10 rounded-lg">
                  {loading ? "Loading network…" : "No fraud rings detected yet."}
                </div>
              )}
            </div>

            <div className="app-card">
              <div className="flex items-center justify-between mb-3">
                <h2 className="font-semibold text-slate-800 dark:text-slate-100">Recent Activity</h2>
                <Link to="/audit-logs" className="text-sm text-primary-600 hover:underline">
                  View All
                </Link>
              </div>
              <ul className="space-y-3.5">
                {auditLogs.map((log) => (
                  <li key={log.id} className="flex items-start gap-2.5 text-sm">
                    <span className="w-2 h-2 rounded-full bg-primary-400 mt-1.5 shrink-0" />
                    <div className="min-w-0">
                      <div className="text-slate-700 dark:text-slate-200 leading-snug">
                        {log.action.replaceAll("_", " ").toLowerCase()}
                        {log.details ? <span className="text-slate-400"> — {log.details}</span> : null}
                      </div>
                      <div className="text-xs text-slate-400">{timeAgo(log.created_at)}</div>
                    </div>
                  </li>
                ))}
                {auditLogs.length === 0 && <li className="text-sm text-slate-400">No recent activity.</li>}
              </ul>
            </div>
          </div>

          {/* Suspicious customers (bonus section beyond the mockup, kept since it's real, useful analyst data) */}
          <div className="app-card">
            <div className="flex items-center justify-between mb-3 flex-wrap gap-2">
              <h2 className="font-semibold text-slate-800 dark:text-slate-100">Suspicious Customers</h2>
              <Link to="/customers" className="text-sm text-primary-600 hover:underline">
                View all customers
              </Link>
            </div>
            <div className="flex items-center gap-2 mb-4 flex-wrap">
              <div className="flex items-center gap-2 bg-slate-50 dark:bg-white/5 border border-slate-100 dark:border-white/10 rounded-lg px-3 py-2 flex-1 min-w-[180px]">
                <svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" className="text-slate-400 shrink-0">
                  <path d={ICONS.search} />
                </svg>
                <input
                  value={customerSearch}
                  onChange={(e) => setCustomerSearch(e.target.value)}
                  placeholder="Search by name or customer ID..."
                  className="bg-transparent text-sm outline-none w-full text-slate-700 dark:text-slate-200 placeholder:text-slate-400"
                />
              </div>
              <select
                value={customerRiskFilter}
                onChange={(e) => setCustomerRiskFilter(e.target.value as CustomerRiskFilter)}
                className="text-sm border border-slate-100 dark:border-white/10 bg-slate-50 dark:bg-white/5 dark:text-slate-200 rounded-lg px-2 py-2"
              >
                <option value="ALL">All Risks</option>
                <option value="HIGH">High</option>
                <option value="MEDIUM">Medium</option>
                <option value="LOW">Low</option>
              </select>
            </div>
            <div className="overflow-x-auto">
              <table className="w-full text-sm">
                <thead>
                  <tr className="text-left text-xs uppercase tracking-wide text-slate-500 dark:text-slate-400 border-b border-slate-100 dark:border-white/10">
                    <th className="py-2 pr-4">Customer</th>
                    <th className="py-2 pr-4">Risk</th>
                    <th className="py-2 pr-4">Risk Score</th>
                    <th className="py-2 pr-4">Suspicious Txns</th>
                    <th className="py-2 pr-4">Devices</th>
                    <th className="py-2 pr-4">Locations</th>
                    <th className="py-2 pr-4">Prior Fraud Reports</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-slate-100 dark:divide-white/5">
                  {filteredCustomers.map((c) => (
                    <tr key={c.id} className="hover:bg-slate-50 dark:hover:bg-white/5">
                      <td className="py-2 pr-4">
                        <Link to={`/customers/${c.customer_id}`} className="text-primary-600 hover:underline">
                          {c.name}
                        </Link>
                        <div className="text-xs text-slate-400">{c.customer_id}</div>
                      </td>
                      <td className="py-2 pr-4">
                        <RiskBadge level={c.risk_level} />
                      </td>
                      <td className="py-2 pr-4 dark:text-slate-300">{c.risk_score.toFixed(1)}</td>
                      <td className="py-2 pr-4 dark:text-slate-300">
                        {c.suspicious_transactions} / {c.total_transactions}
                      </td>
                      <td className="py-2 pr-4 dark:text-slate-300">{c.devices_used}</td>
                      <td className="py-2 pr-4 dark:text-slate-300">{c.locations_used}</td>
                      <td className="py-2 pr-4 dark:text-slate-300">{c.previous_fraud_reports}</td>
                    </tr>
                  ))}
                  {!loading && filteredCustomers.length === 0 && (
                    <tr>
                      <td colSpan={7} className="py-4 text-center text-slate-400">
                        {suspiciousCustomers.length === 0 ? "No suspicious customers flagged yet." : "No customers match your filters."}
                      </td>
                    </tr>
                  )}
                </tbody>
              </table>
            </div>
          </div>

          <div className="grid grid-cols-1 sm:grid-cols-2 gap-6">
            <FingerprintTable title="Suspicious Devices" columnLabel="Device ID" rows={suspiciousDevices} loading={loading} />
            <FingerprintTable title="Suspicious IP Addresses" columnLabel="IP Address" rows={suspiciousIps} loading={loading} />
          </div>
        </div>

        {/* Right rail */}
        <div className="space-y-6">
          <div className="app-card">
            <div className="flex items-center justify-between mb-4">
              <h2 className="font-semibold text-slate-800 dark:text-slate-100">System Health</h2>
              <span className={`text-xs font-medium px-2 py-1 rounded-full ${error ? "bg-red-50 text-red-600 dark:bg-red-500/10 dark:text-red-400" : "bg-emerald-50 text-emerald-600 dark:bg-emerald-500/10 dark:text-emerald-400"}`}>
                {error ? "Attention needed" : "All Systems Operational"}
              </span>
            </div>
            <ul className="space-y-3 text-sm">
              <li className="flex items-center justify-between">
                <span className="text-slate-500 dark:text-slate-400">API Status</span>
                <span className={`font-medium ${error ? "text-red-600" : "text-emerald-600"}`}>{error ? "Unreachable" : "Online"}</span>
              </li>
              <li className="flex items-center justify-between">
                <span className="text-slate-500 dark:text-slate-400">ML Model</span>
                <span className={`font-medium ${error ? "text-red-600" : "text-emerald-600"}`}>{error ? "Degraded" : "Healthy"}</span>
              </li>
              <li className="flex items-center justify-between">
                <span className="text-slate-500 dark:text-slate-400">Database</span>
                <span className={`font-medium ${error ? "text-red-600" : "text-emerald-600"}`}>{error ? "Error" : "Connected"}</span>
              </li>
              <li className="pt-2 mt-1 border-t border-slate-100 dark:border-white/10 flex items-center justify-between">
                <span className="text-slate-500 dark:text-slate-400">Transactions/min</span>
                <span className="font-medium text-slate-800 dark:text-slate-100">{loading ? "—" : transactionsPerMinute}</span>
              </li>
              <li className="flex items-center justify-between">
                <span className="text-slate-500 dark:text-slate-400">Last Updated</span>
                <span className="font-medium text-slate-800 dark:text-slate-100">{lastRefreshed ?? "—"}</span>
              </li>
            </ul>
          </div>

          <div className="app-card">
            <h2 className="font-semibold text-slate-800 dark:text-slate-100 mb-4 flex items-center gap-1.5">
              <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" className="text-red-500">
                <path d={ICONS.triangle} />
              </svg>
              Top Risk Factors
            </h2>
            <div className="space-y-3.5">
              {topRiskFactors.map((f) => (
                <div key={f.label}>
                  <div className="flex items-center justify-between text-xs mb-1">
                    <span className="text-slate-600 dark:text-slate-300 font-medium">{f.label}</span>
                    <span className="text-slate-400">{f.pct}%</span>
                  </div>
                  <div className="h-1.5 rounded-full bg-slate-100 dark:bg-white/10 overflow-hidden">
                    <div className={`h-full rounded-full ${f.color}`} style={{ width: `${f.pct}%` }} />
                  </div>
                </div>
              ))}
              {topRiskFactors.length === 0 && <p className="text-sm text-slate-400">Not enough alert data yet.</p>}
            </div>
          </div>

          <div className="rounded-2xl bg-gradient-to-br from-primary-600 to-primary-800 text-white p-5 shadow-soft">
            <div className="flex items-center gap-2 mb-3">
              <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                <path d={ICONS.bulb} />
              </svg>
              <span className="text-sm font-semibold">AI Insights</span>
              <span className="text-[10px] font-bold uppercase tracking-wide bg-white/20 rounded-full px-1.5 py-0.5">Beta</span>
            </div>
            {peakDay ? (
              <p className="text-sm leading-relaxed mb-4 text-primary-50">
                The system detected an unusual pattern in transaction velocity — {peakDay.date} saw {peakDay.total} suspicious
                transactions, including {peakDay.high} high-risk.
              </p>
            ) : (
              <p className="text-sm leading-relaxed mb-4 text-primary-50">Not enough data in this range to surface a trend yet.</p>
            )}
            <Link to="/alerts" className="inline-flex items-center gap-1.5 text-sm font-semibold bg-white/15 hover:bg-white/25 rounded-lg px-3 py-1.5 transition-colors">
              View Details →
            </Link>
          </div>
        </div>
      </div>
    </div>
  );
}

function FingerprintTable({
  title,
  columnLabel,
  rows,
  loading,
}: {
  title: string;
  columnLabel: string;
  rows: SuspiciousFingerprint[];
  loading: boolean;
}) {
  return (
    <div className="app-card">
      <h2 className="font-semibold text-slate-800 dark:text-slate-100 mb-3">{title}</h2>
      <div className="overflow-x-auto">
        <table className="w-full text-sm">
          <thead>
            <tr className="text-left text-xs uppercase tracking-wide text-slate-500 dark:text-slate-400 border-b border-slate-100 dark:border-white/10">
              <th className="py-2 pr-4">{columnLabel}</th>
              <th className="py-2 pr-4">Customers</th>
              <th className="py-2 pr-4">Txns</th>
              <th className="py-2 pr-4">High Risk</th>
              <th className="py-2 pr-4">Avg Score</th>
            </tr>
          </thead>
          <tbody className="divide-y divide-slate-100 dark:divide-white/5">
            {rows.map((r) => (
              <tr key={r.value} className="hover:bg-slate-50 dark:hover:bg-white/5">
                <td className="py-2 pr-4 font-mono text-xs dark:text-slate-300">
                  {r.value}
                  {r.shared_across_customers && (
                    <span className="ml-2 px-1.5 py-0.5 rounded bg-red-100 text-red-700 dark:bg-red-500/20 dark:text-red-300 text-[10px] font-semibold align-middle">
                      SHARED
                    </span>
                  )}
                </td>
                <td className="py-2 pr-4 dark:text-slate-300">{r.customer_count}</td>
                <td className="py-2 pr-4 dark:text-slate-300">{r.transaction_count}</td>
                <td className="py-2 pr-4 dark:text-slate-300">{r.high_risk_count}</td>
                <td className="py-2 pr-4 dark:text-slate-300">{r.avg_risk_score.toFixed(1)}</td>
              </tr>
            ))}
            {!loading && rows.length === 0 && (
              <tr>
                <td colSpan={5} className="py-4 text-center text-slate-400">
                  Nothing flagged in this range.
                </td>
              </tr>
            )}
          </tbody>
        </table>
      </div>
    </div>
  );
}
